### ISSUE TITLE
jio tv version 3.2.11 error

### ISSUE THREAD

**Issue by deven13j** [kiranreddyrebel/kiranreddyrebel.github.io#4]
gettin attribute error, 'bool' has no attribute get

**Comment by kiranreddyrebel** [comment]
You need to remove completely old plugin. Its cached in addon folder. Remove all folders in addon folder or else uninstall kodi.

**Comment by deven13j** [comment]
let me try it

**Comment by shri1990** [comment]
Even after Kodi v20.5 uninstall and reinstall, still getting same error

**Comment by deven13j** [comment]
```
2024-07-25 22:16:27.948 T:6719     info <general>: CAndroidUtils: Preferred refresh rate: 60.000004
2024-07-25 22:16:27.948 T:6719     info <general>: CAndroidUtils: Current resolution: 2313x1080 2313x1080 @ 60.000004 - Full Screen
2024-07-25 22:16:27.985 T:6719     info <general>: CAndroidUtils: Preferred refresh rate: 60.000004
2024-07-25 22:16:27.985 T:6719     info <general>: CAndroidUtils: Current resolution: 2313x1080 2313x1080 @ 60.000004 - Full Screen
2024-07-25 22:16:28.656 T:6719     info <general>: CAndroidUtils: Preferred refresh rate: 60.000004
2024-07-25 22:16:28.657 T:6719     info <general>: CAndroidUtils: Current resolution: 2313x1080 2313x1080 @ 60.000004 - Full Screen
2024-07-25 22:16:31.309 T:16782    info <general>: Loading skin file: MyVideoNav.xml, load type: KEEP_IN_MEMORY
2024-07-25 22:16:31.496 T:17051 warning <general>: Setting most video properties through ListItem.setInfo() is deprecated and might be removed in future Kodi versions. Please use the respective setter in InfoTagVideo.
2024-07-25 22:16:32.838 T:17051    info <general>: Skipped 2 duplicate messages..
2024-07-25 22:16:32.838 T:17051 warning <general>: [py.warnings] /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.urllib3/lib/urllib3/connectionpool.py:1099: InsecureRequestWarning: Unverified HTTPS request is being made to host 'jiotvapi.cdn.jio.com'. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.io/en/latest/advanced-usage.html#tls-warnings
                                                     warnings.warn(

2024-07-25 22:16:32.914 T:17051   error <general>: [JioTV.support] 'bool' object has no attribute 'get'
                                                   Traceback (most recent call last):
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/support.py", line 306, in run_callback
                                                       redirect = parent_ins(route, arg_params, self.callback_params)
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 196, in __call__
                                                       session_data = self._process_results(results)
                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 210, in _process_results
                                                       listitems = validate_listitems(results)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.codequick/lib/codequick/route.py", line 39, in validate_listitems
                                                       raw_listitems = list(raw_listitems)
                                                                       ^^^^^^^^^^^^^^^^^^^
                                                     File "/storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.jiotv/resources/lib/main.py", line 202, in show_listby
                                                       GENRE_MAP = dictionary.get("channelCategoryMapping")
                                                                   ^^^^^^^^^^^^^^
                                                   AttributeError: 'bool' object has no attribute 'get'
2024-07-25 22:16:39.598 T:16782    info <general>: CWinSystemAndroid::DestroyWindow
2024-07-25 22:16:40.483 T:6719     info <general>: Got device sleep intent
2024-07-25 22:16:40.986 T:16782    info <general>: OnSleep: Running sleep jobs
2024-07-25 22:16:40.997 T:16782 warning <general>: OnSystemSleep: Not calling add-on 'pvr.iptvsimple'. Add-on not (yet) connected.
```

**Comment by PadekarPratap** [comment]
@kiranreddyrebel Is the Jio TV addon working now? Even I'm getting the same error. I request you to please continue maintaining it 🙏

**Comment by PadekarPratap** [comment]
@kiranreddyrebel bro, I uninstalled and reinstalled the Kodi version you specified. However I'm still getting this error: (SS shared below)

![WhatsApp Image 2024-07-26 at 6 36 45 PM](https://github.com/user-attachments/assets/e2688e49-3085-4bba-9eda-db4ebc7dd476)

![WhatsApp Image 2024-07-26 at 6 36 45 PM (1)](https://github.com/user-attachments/assets/07767ebd-033f-4100-a99b-fb786d8900cd)

**Comment by kiranreddyrebel** [comment]
Looking into it bro.

**Comment by PongLeniss** [comment]
Bro please provide full method how to install

**Comment by kiranreddyrebel** [comment]
Fixed error, now working jiotv

**Comment by deven13j** [comment]
let me try and update you soon

**Comment by shri1990** [comment]
> Fixed error, now working jiotv @deven13j @shri1990 @PadekarPratap - Guys make sure you remove old plugin completely also from cache folder or else you can do reinstall kodi completely so that while installing plugin doesn't get install from cache folder (kodi).
> 
> @PongLeniss
> 
> Steps
> 
> Install Kodi latest.
> 
> Then disable auto updates in settings of addons
> 
> Enable "Unknown sources"
> 
> (Disable auto update in addon settings)
> 
> Goto settings > File manager
> 
> Add source
> 
> https://kiranreddyrebel.github.io/
> 
> save with any name.
> 
> Go back, click addons > install from zip
> 
> Click that name you saved source.
> 
> Click repository.kiranreddyrebel.zip
> 
> Once installed ,Exit kodi.
> 
> Open kodi, settings > addons > install from repository
> 
> Click kiranreddyrebel repository > Video addons > jioTV - version 2.3.11
> 
> It will install jio plugin
> 
> Rest you know what to do. Jio add-on>configure>setup IPTV etc etc.
> 
> Thanks to comments.

Its working man.. Thank you so much.. Appreciate your efforts

**Comment by deven13j** [comment]
No luck for me, getting problem with login, I will try with clean fresh kodi install soon

**Comment by rahulc292** [comment]
Working now without any error. Thank you Kiran

**Comment by PadekarPratap** [comment]
@deven13j  use latest version of Kodi

**Comment by deven13j** [comment]
> @deven13j use latest version of Kodi

@PadekarPratap I am using latest version, i try on my Android as well as on windows kodi as well. Facing issue with login module after entering OTP nothing happend and channels are not working. once open any channel again it go for login process

**Comment by kiranreddyrebel** [comment]
> > @deven13j use latest version of Kodi
> 
> @PadekarPratap I am using latest version, i try on my Android as well as on windows kodi as well. Facing issue with login module after entering OTP nothing happend and channels are not working. once open any channel again it go for login process 

First add jio number in accounts
Then apply settings.
Then accounts>login (otp method)

Try this.

Once done.
Click setup iptv so that the epg updates.

I'm trying to update epg (tobalan's epg workflow forked) .
Will updatr soon. @rahulc292

**Comment by PongLeniss** [comment]
Thank you @kiranreddyrebel it's working but seems like sony channel's not working but still i appreciate your efforts

**Comment by kiranreddyrebel** [comment]
> Thank you @kiranreddyrebel it's working but seems like sony channel's not working but still i appreciate your efforts 

Welcome. Yes sony not working. I will try adding external links from sonyliv soon.

**Comment by SkieyeN** [comment]
Hii @kiranreddyrebel

Working on the new plugin, but found a  bug, whenever Gemini tv is open chutti tv is playing.. Seems some mapping issue. Please check and confirm.

**Comment by SkieyeN** [comment]
😔 Suddenly Not working, header error, connectivity issue.

Does anyone facing same issue..

**Comment by SkieyeN** [comment]
@kiranreddyrebel

**Comment by xysterv** [comment]
Yes. It stopped working again.

**Comment by kiranreddyrebel** [comment]
> Yes. It stopped working again.

Bro, its working. Please clean install kodi + remove plugin completely.

Install 2.3.12 version.

**Comment by xysterv** [comment]
Thanks. Its working

**Comment by kiranreddyrebel** [comment]
> No luck for me, getting problem with login, I will try with clean fresh kodi install soon

Does it worked ?

**Comment by SkieyeN** [comment]
@kiranreddyrebel

Suddenly stopped working, no errors but channel is getting skipped.

**Comment by kiranreddyrebel** [comment]
> @kiranreddyrebel
> 
> Suddenly stopped working, no errors but channel is getting skipped. 

When did it stopped working. Its working bro. Just now I checked.

Do one thing remove everything , clean cache and reinstall kodi.

**Comment by SkieyeN** [comment]
Just now I checked not working, channels are getting skipped without error message too.. @kiranreddyrebel

**Comment by kiranreddyrebel** [comment]
> Just now I checked not working, channels are getting skipped without error message too.. @kiranreddyrebel 

Check after reinstall and cleaning cache bro.

**Comment by SkieyeN** [comment]
![IMG20240816160430](https://github.com/user-attachments/assets/02cb2ec5-4c68-4cae-b576-1c19428eed26)

Attached the snapshot, while selecting the channel and playing.. On top it's shows now playing but skipping.

**Comment by SkieyeN** [comment]
@kiranreddyrebel

Sun channels, zee channels(Tamil and Telugu) are not not playing, news channels are working..

Does any one facing the same issue, please do confirm.

@kiranreddyrebel you can also check and confirm.

**Comment by SkieyeN** [comment]
Any one else facing the same or only me, please confirm so that I will try to reinstall again and check..

**Comment by Karthikshreeram** [comment]
> Fixed error, now working jiotv @deven13j @shri1990 @PadekarPratap  - Guys make sure you remove old plugin completely also from cache folder or else you can do reinstall kodi completely so that while installing plugin doesn't get install from cache folder (kodi).
> 
>  @PongLeniss 
>  
>  
> 
> Steps
> 
> Install Kodi latest.
> 
> Then disable auto updates in settings of addons
> 
> Enable "Unknown sources"
> 
> (Disable auto update in addon settings)
> 
> Goto settings > File manager
> 
> Add source
> 
> https://kiranreddyrebel.github.io/
> 
> save with any name.
> 
> Go back, click addons > install from zip
> 
> Click that name you saved source.
> 
> Click repository.kiranreddyrebel.zip
> 
> Once installed ,Exit kodi.
> 
> Open kodi, settings > addons > install from repository
> 
> Click kiranreddyrebel repository > Video addons > jioTV - version 2.3.11
> 
> It will install jio plugin
> 
> Rest you know what to do. Jio add-on>configure>setup IPTV etc etc.
> 
> Thanks to comments.
> 

This is not working now

**Comment by kiranreddyrebel** [comment]
what is not working Karthik ? any error image ? please attach image.

**Comment by Karthikshreeram** [comment]
![VideoCapture_20241209-122431.jpg](https://github.com/user-attachments/assets/73ebe453-4fb3-42d2-b906-d7892095e511)

![VideoCapture_20241209-122439.jpg](https://github.com/user-attachments/assets/5af91b62-4321-4ea2-88a5-628bc136508c)

![VideoCapture_20241209-122449.jpg](https://github.com/user-attachments/assets/6dd0b739-69d5-4ebd-abf2-fb1e87740834)

Sorry for the delayed response,  enclosed the photos of the error message
